### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [rodpat/splurty#1]
On mobile things don't look as good as they could be.
One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.
Let me know in the comments once you figured that step out :)

**Comment by rodpat** [comment]
Hello Mike, 

Thanks for your feedback, could you tell me how to add that meta tag, please?

Is this ` <meta name="viewport content=width=device-width, initial-scale=1.0">,`  just below "title tag" in application.html.erb file?

Best regards,

**Comment by Mikeysax** [comment]
Google is your friend! Let me know when you figure it out :smile: 

Learning how to learn and figure unfamiliar things out in development are keys to success!

**Comment by rodpat** [comment]
Well, I think I found it, just below `<head>` tag.

**Comment by Mikeysax** [comment]
I would check this out: https://v4-alpha.getbootstrap.com/getting-started/introduction/#responsive-meta-tag

Make the changes to your project and let me know when it's pushed to this repository.

**Comment by rodpat** [comment]
Ok, I added a new commit.

**Comment by Mikeysax** [comment]
:+1:
